# Generated by Django 4.2.3 on 2023-09-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="profiles",
            field=models.ManyToManyField(
                blank=True, related_name="certificates", to="projects.profile"
            ),
        ),
    ]
